var bio =[
  { img:"image/singlenosemicroscope.jpg", name : "Single Nose Microscope", price: "On Request", description: "Metal construction eyepiece 10x objective: 10x total magnification: 100x plane concave mirror on gamble mount for illumination gives clear images easy to operate ideal for school & kids." , Specification : " Mechanical Tube Length 160 mm Achromatic Objectives 10X Fine AdjustmentStage Area 85 x 90 mm Illuminator Concave - Plano Mirror 40 mm. Ø"},
  { img:"image/juniormedical.jpg", name : "JUNIOR MEDICAL  MICROSCOPE (moveable condenser)", price :"On Request",description:" Best resolution optical system microscope,Eyepieces H10x & H 15X (2Nos),Parfocal Achro-Objectives 10x, 40x/45x Retractable SL,Rack & Pinion focus system with safety stopper,Fine focus by slow motion mechanism,Plain square stage with two stage clips,Efficient NA 1.25 condenser with iris diaphragm moveable on rack & pinion.Plano-concave mirror provides transmitted light source"},
  {img:"image/MedicalMicroscope.JPG", name:" MEDICAL / LABORATORY MICROSCOPE", price: 35,description: "High resolution optical system microscope for Educational purpose,Body inclinable to 90° on base,Eyepieces H10x & H15X (2Nos),Parfocal Achro-Objectives 10x, 40x/45xSL, 100xOil,Rack & Pinion focus system with safety stopper, Fine focus by slow motion mechanism,Plain square stage with two stage clips,Efficient NA 1.25 condenser with iris diaphragm moveable on rack & pinion.,Plano-concave mirror provides transmitted light source"},
   {img:"image/travellingMicroscope.jpg ",name:"Travelling Microscope",price:"On Request",description:" Vernier Reading Microscope or Travelling Microscope. 0.1 mm,horizontal Scale Is Graduated Up to 20 cm,vertical Scale Is Graduated Up to 15 cms, Cast Iron Heavy Bed With Brass levelling Screws, 10 x Remsdon Eye Piece, Achromatic Objective With F.l. 50-75 mm,vertical And Horizontal Slide Can Be Clamped At Any Position. "},
   {img:"image/binocularmicroscope.jpg",name:" Binocular Microscope",price:"On Request",description:" * Heavy cast metal rectangular body . * Built in illumination by 6V-20W halogen bulb with continuously variable intensity control ( solid stage transformer). * Provision for day light illumination by plano concave mirror . * With Binocular Head rotatable through 360Deg. * Abbe Type N.A. 1.25 condenser with Iris Diphragm & Filter holder moveable up & down by Rack & Pinion. * Finished with highly resistant beautiful stoving finish . Includes PAIR of Wide Field Eye Pieces 10x and Co-Excel Mechanical Stage "},
   {img:"image/projectionmicroscope.jpg ",name:"Projection Microscope",price:"On Request",description:"Projection Microscope . 150 mm Dia screen Projection Microscope. Objectives: 10 x, 20 x. Eyepiece: 10 x. Magnification: 100 x - 200 x Plain stage with slide holding clips. Rack and Pinion coarse focus. 12 V Halogen projection bulb "},
   {img:"image/newtonringmicroscope.jpg ",name:"Newton Ring Microscope",price:"On Request",description:" Compact instrument with full arrangements for conducting Newton's Ring experiment. A standard microscope unit with 30x magnification and rotatable cross line eye piece. Focusing of microscope is through Rack and Pinion. Longitudinal movement of 26 mm is done by rotating the drum provided which reads up to 0.001cm. Complete with optical glass and convex lens inside a metal case. Packed in a sturdy wooden box along with all standard accessories "},
  {img:"image/polarizingmicroscope.jpg ",name:"STUDENT POLARIZING MICROSCOPE",price:"On Request",description:"For study of thin sections of rocks and minerals showing birefringent properties. Provided with Polarizer, Analyser and Bertrand lens. Strain free objectives 10x & 40x and Two Huyghenian Eyepieces 10x (Cross hair) and 15x, Circular centering type rotatable graduated stage.  "},
    {img:"image/optics.jpg ",name:"Phase Contrast Dark Field Microscope",price:"On Request",description:"High quality optics, "},
  {img:"image/TISSUEBATH.jpg  ",name:"Tissue Floatation Bath",price:"On Request",description:" Double walled round construction. Inner chamber stainless steel/black anodized aluminum and outer made out of mild steel painted in epoxy powder coating. Thermostatic control, temperature range from ambient to 80°C. Complete with indicators, wire & plug. To work on 220V AC.Inner Chamber Sizes are available :200x75 mm, 250x175 mm"},
  {img:"image/paraffinembeddingwaxbath.jpg  ",name:"Paraffin Embedding Wax Bath",price:"On Request",description:"Thermostatically controoled. Double walled with cupes and sleeves for glass tubes. Temprature up to 95° C with accuracy of + 0.5° to 1° C 4 Cups and 6 sleeves "},
    {img:"image/slidecabinet.jpg  ",name:"Slide Cabinet",price:"On Request",description:"For keeping 75mm x 25mm glass slides in vertical position in plastic grooves individually. Cabinet frame of MDF with melamine lamination. Hinged door with lock is lined with velvet. Drawer frame of MDF/ ABS Plastic fitted with knob, index card holder and Extra drawer in base with printed index sheets. "},
    {img:"image/HumanSkeltonDisarticulatedFiber.jpg ",name:" Human Skeleton Disarticulated Fiber Model ",price:"On Request",description:"Disarticulated Skeleton model(plain white).Made of fiber glass & pvc.disarticulated adult skeleton life size disarticulated skeleton will encourage students to learn various bones of an adult human. It is a visual aid for instruction of anatomy for students, doctors, nurses or anyone interested in human skeleton."},
    {img:"image/HumanSkeletonArticulated.jpg ",name:" Human Skeleton Articulated Fiber Model ",price:"On Request",description:"Life size, articulated adult skeletonarms & legs are removable. .Approx. 5 Feet in height. Made of fiber glass & pvc "},
    /*{img:"image/  ",name:"",price:"On Request",description:" "},
    {img:"image/  ",name:"",price:"On Request",description:" "},
    {img:"image/  ",name:"",price:"On Request",description:" "},
    {img:"image/  ",name:"",price:"On Request",description:" "},*/


];
