var plasticWare = [
  {img:"image/droppingbottles.jpg", name:"DROPPING BOTTLES", price: "On Request", description:"Blown in Low Density Polyethylene, Polylab Dropping Bottles dispense small uniform drops of liquids when pressed lightly.", specs:"60 ml, 125 ml", material:"Density Polyethylene"},
  {img:"image/dropBottleEuro.jpg", name:"DROPPING BOTTLES (EURO DESIGN)", price:"On Request", description:"These bottles made in low density polyethylene dispense small uniform drops of liquids.The unique feature of these bottles is the screw cap with lid.", specs:"15ml, 30ml, 60ml, 125ml, 250ml, 500ml", material:"Low Density Polyethylene"},
  {img:"image/regentbottelsnarrowmouth.jpg", name:"REGENT BOTTLES (NARROW MOUTH)", price:"On Request", description:"These Narrow Mouth Regent Bottles are available in polypropylene. The PP bottles are rigid, translucent and have excellent contact clarity. These bottles can be autoclaved filled as well as empty. The polypropylene Cap has a built in seal ring to make these bottles leakproof.", specs:"4ml, 8ml, 15ml, 30ml, 60ml, 125ml, 250ml, 500ml, 1000ml", material:"Polypropylene"},
  {img:"image/reagent_wide.jpg", name:"REAGENT BOTTLES (wide mouth)", price:"On Request", description:"These wide mouth reagent bottles are available in polypropylene. The PP bottles are rigid, translucent and have excellent contact clarity. These bottles can be autoclaved filled as well as empty. The polypropylene cap has a built in seal ring to make these bottles leekproof", specs:"30ml, 60ml, 125ml, 250ml, 500ml, 1000ml", material:"Polypropylene"},
  {img:"image/narrowmouthbottel.jpg", name:"NARROW MOUTH BOTTLE", price:"25", description:"This autoclavable bottle, made of polypropylene, can be used for storing & transferring chemicals and other reagents safe & sound.", specs:"4000 ml", material:"Polypropylene"},
  {img:"image/wideMouthSquareBottle.png", name:"WIDE MOUTH SQUARE BOTTLE", price:"On Request", description:" This autoclavable bottle, made of polypropylene, can be used for storing & shipping chemicals & reagents. Being wide mouthed, it is always convenient to pour in & take out the reagents. The built in depressions on two sides provide excellent grip while holding this bottle.", specs:"4000 ml", material:"Polypropylene"},
  { img:"image/HEAVYDUTYVACCUBOTTLE.png", name:"HEAVY DUTY VACCUM BOTTLE", price:"On Request", description:"This autoclavable bottle, made of polypropylene, has thick walls, is rugged & can be used for repeated applications of vacuum.",specs:"2000 ml",material:"Polypropylene"},
   { img:"image/carboy.jpg", name:"CARBOY", price:"On request", description:"Carboys, made of polypropylene, are much lighter than glass. These autoclavable, dependable & durable carboys are provided with wide handles making it convenient while carrying or pouring purposes.",specs:"10Ltrs.	20 Ltrs.",material:"Polypropylene" },
  {img:"image/CARBOYWITHSTOPCOCK.png", name: "CARBOY WITH STOP COCK", price:"0n request", description:" These polypropylene Carboys are autoclavable, dependable & durable. These are also equipped with a leak proof spigot screwed to the body. These carboys are an excellent replacement for glass carboys and are used for storing & dispensing distilled water & other laboratory solutions.",specs:"10 Ltrs.20 Ltrs.",material:"Polypropylene"},
{ img:"image/AspiratorBottles.jpg", name:" Aspirator Bottles", price:"On Request", description:"Aspirator Bottles are made of polypropylene and are therefore much lighter than glass. Theseare autoclavable, dependable & durable. The leakproof spigot screwedto the bottle body requires only a half turn to open or close. Thesebottles are used for storing or dispensing distilled water & otherlaboratory solutions. Threads should be totally disengaged beforeautoclaving.",specs:" 2 Ltrs. 5 Ltrs.10 Ltrs.20 Ltrs.",material:":Polypropylene" },
  {img:"image/WashBottles.jpg", name: "Wash Bottles", price:"On Request", description: "Wash Bottles are made of low density polyethylene which gives these bottles a translucent &unbreakable character. Solutions can be poured easily by squeezing thebottle lightly. The cap is fitted with a flexible polyethylenedelivery tube which can be aimed wherever required.",specs:" 125 ml.250 ml.500 ml.1000 ml.",material:" Low Density Polyethylene" },
   {img:"image/WashBottles(NewType).jpg", name:" Wash Bottles (New Type)", price:"On Request", description:" These bottles are also made of low density polyethylene and aretherefore translucent & unbreakable. The distinguishing feature thatthese bottles contain is the built in delivery tube making it aone-piece wash bottle. These bottles are graduated on the outersurface to give an approximate idea about the volume of solutionsfilled or dispensed.",specs:" 125 ml.250 ml.500 ml.",material:" Low Density Polyethylene" }, 
  {img:"image/specimanjar.jpg", name:" Specimen Jar ( Gas Jar)", price:"On Request", description:" These transparent specimen jars,used for preserving different specimens in the lab are provided with cap that fits in tight. Thesejars provided excellent protection to the species preserved in it ",specs:" φ 50 mm X h 150 mm ",material:" Polystyrene " }, 
  {img:"image/fisherclamp.jpg", name:"Fisher Clamp", price:" On Request ", description:" These Clamps are moulded in Polypropylene making it completely corrosion-proof. The spring loadedjack in the middle provides a vice like grip to the burette andprevents it from slipping. Two tapered wedges are provided to ensurefirm grip on rods having dia 1/2 or 3/8", specs:"Fisher Clamp - Single Fisher Clamp- Double",material:"Polypropylene"},
  {img:"image/funnelholder.jpg", name:"Funnel Holder", price:" On Request ",description:" Made of Polypropylene, these corrosion free funnel holders can hold funnels with dia 3 inch  to 6 inch. The extra plate provided can be placed to hold funnels bearing dia 1inch  to 3 inch. Two tapered wedges are provided to ensure firm grip on Rods havingdia 1/2 or 3/8",specs:" Funnel Holder - Single Funnel Holder - Double", material:"Polypropylene"},
{img:"image/retortstand.jpg ", name:" Retort Stand ", price:"On Request", description:" These non-corrosive, mouldedretort stands provide excellent replacement for the metal ones. Eventhe metallic rod has a polypropylene covering making it non-corrosive.The rod measuring 12.5 mm X 750 mm can be screwed into the heavy base giving way to a perfectly stable retort stand.",specs:" 225 x 150 mm-Side Hole300 x 200 mm-Centre Hol300 x 200 mm-Side Hole",material:" Polystyrene/Polypropylene" },
{img:"image/flaskstand.jpg", name:" Flask Stand", price:"On Request", description:" Moulded in Polypropylene, this flask stand gives a stair-like top view. Every step provides excellent support to the round bottom flask at every point of contact. Thisflask stand can hold round bottom flasks up to 10 Ltr. Capacity. This stackable flask stand can also be steam autoclaved.",specs:"",material:" Polypropylene" },
  {img:"image/rack.jpg", name:"  Rack For Scintillation Vial ", price:"On Request", description:" These Racks for scintillation Vials, moulded in Polypropylene, are autoclavable & corrosion resistant. There is an individual rack for both 8 ml. & 20ml. vials. These rugged & stable racks can hold scintillation vials for convenient storage, handling & sample preparations.",specs:" Rack for 90 vials of 8 ml. capacity Rack for 50 vials of 20 ml. capacity",material:" Polypropylene" },
  {img:"image/universalmultirack.jpg", name:" Universal Multi Rack", price:"On Request", description:"This rack is anexcellent lab apparatus compatible with different sizes of tubes. Fours ides of this rack can be used for tubes of φ30mm, φ20mm, φ17mm &φ12mm.",specs:"",material:"Polypropylene" },
  {img:"image/nestlercylinderstand.jpg", name:"Nestler Cylinder Stand", price:"On Request", description:"This stand, as the name suggests, is used for keeping nestlercylinders. Made of polypropylene, this stand is available in two sizes, one for 50ml nestler cylinder & other for 100ml. nestlercylinder.",specs:"",material:"Polypropylene" },
 {img:"image/testtubestand.jpg", name:"Test Tube Stand", price:"On Request ", description:"This autoclavable stand is perhaps the most commonly used test tube stand in various laboratories. For better visibility, this 6 place rack is endsupported by 2 columns. The top plate has 2 holes for holding 25 mmdia test tubes, four holes to hold 16 mm dia tubes where as the basehas corresponding hemispherical wells. It also has six vertical pinsfor drying tubes. Another option available in this section is a testtube stand in which all the holes in the top plates can hold 25 mm diatubes.",specs:"",material:"Polypropylene" },
  {img:"image/testtubestand(round).jpg", name:"Test Tube Stand (Round)", price:"On Request", description:"A handy, little,space saver, this circular twelve place polypropylene test tube standhas four 25 mm dia holes & eight 19 mm dia holes in its top plate. Thebase has matching hemispherical wells & 16 vetical pins for dryingtubes surrounded by a trough to catch drippings. This autoclavable rack can be easily disassembled for cleaning purpose.",specs:"",material:"Polypropylene"},
   {img:"image/testtubestand(3).jpg", name:"Test Tube Stand (3-tier)", price:"On Request", description:" These ingenious racks with a 3-tier design provide clear view of the tube contents &convenient insertion & removal of tubes. The PC Rack has transparent upper & middle plates where as in PP racks, every part is colored &opaque. These autoclavable racks can with stand sub-freezing temperatures.",specs:"13 mm x 31 Tubes 16 mm x 31 Tubes 20 mm x 20 Tubes 25 mm x 12 Tubes 25 mm x 18 Tubes 32 mm x 12 Tubes 25 mm x 36 Tubes 13 mm x 18 Tubes 15 mm x 18 Tubes 18 mm x 12 Tubes 13 mm x 62 Tubes 16 mm x 62 Tubes mm x 40 Tubes 13 mm x 48 Tubes 13 mm x 72 Tubes",material:"Polypropylene" },
 {img:"image/animalcage.jpg", name:"Animal Cage", price:"On Request", description:" These Cages provide excellent shelter for different animal species in the laboratory. The metallic top provides proper ventilation and has provisions for feeding the species.Available in two different sizes.290 X 220 X 140 mm and 430 X 270 X 150 mm.",specs:"290 X 220 X 140 mm and 430 X 270 X 150 mm",material:"Polypropylene/Stainless Steel" },
   {img:"image/animalcagetwingrill.jpg", name:"Animal Cage(Twin Grill) ", price:"On Request", description:"Adding in line with the existing range, these animal cages are provided with a stainless steel grill at the bottom of the cage to provide a clean surface for the species to move on..Available in two different sizes.290 X 220 X 140 mm and 430 X 270 X 150 mm",specs:" sizes.290 X 220 X 140 mm and 430 X 270 X 150 mm",material:"Polypropylene/Stainless Steel" },
   {img:"image/waterbottleanimalcage.jpg", name:"Water Bottle-Animal Cage", price:"On Request", description:" These water bottles prove to be an excellent accessory for the species kept in the cages. Available in two sizes 125 ml. and 250 ml. ",specs:" sizes 125 ml. and 250 ml",material:"Polypropylene/Stainless Steel" },
 {img:"image/instrumenttray.png", name:"Instrument Tray", price:"On Request", description:" This autoclavable trays have cover which fits into groove of trays to minimize spillage of meterial. Smaller size can be used to sterilize small instruments whereas the larger size allows pipettes to be fully immersed in disinfectant prior to sterilisizing.sizes available 220 x 150 x 70 mm and 450 x 150 x 70 mm.",specs:" 220 x 150 x 70 mm and 450 x 150 x 70 mm.",material:"Polypropylene" },
{img:"image/carriertray.png ", name:"Carrier Tray ", price:"On Request", description:" This autoclavable polypropylene Tray has a unique feature i.e its handle which proves really helpful in carrying reagents or laboratory apparatus from one place to another,single handedly . size :380 x 240 x 115 mm",specs:" size :380 x 240 x 115 mm",material:"polypropylene" },
{img:"image/utilitytray.png", name:" Utility Tray", price:"On Request", description:" The Utility Tray and as the name suggests this polypropylene Trays can be utilized for purposes ranging from drying glassware to sterilizing and to store any laboratory apparatus. size available 375 x 350 x 130 mm",specs:"375 x 350 x 130 mm",material:" polypropylene" },
   {img:"image/laboratorytray.png", name:"Laboratory Tray", price:"On Request", description:"  Laboratory Tray moulded in polypropylene is a multipurpose tray that can be used for sterilizing, drying glassware, porcelainware & other laboratory instruments.These steam  autoclavable trays have tapered walls which prove good for nesting.sizes available 450 x 350 x 75 mm and 375 x 300 x 75 mm",specs:" 450 x 350 x 75 mm and 375 x 300 x 75 mm",material:"polypropylen"}, 
 {img:"image/drainingbasket.png", name:"Draining Basket", price:"On Request ", description:" As the name suggests,this basket with wide net like structure on all sides prove really useful for draining different laboratory appratus after washing them.made of polypropylene,this basket can be reapeatedly autoclaved. size :400 x 400 x 100 mm ",specs:" size :400 x 400 x 100 mm",material:" polypropylene" },
{img:"image/testtubebaskets.png", name:"Test Tube Baskets", price:"On Request", description:" Test Tube Baskets are made of Polypropylene.These autoclavable,unbreakable and non-corrosive Baskets are ideal for rinsing & draining glassware.These are also useful for storage of test tubes or culture tubes during sterilization or incubation. sizes available 140 x 120 x 110 mm and 160 x 160 x 160 mm",specs:" sizes 140 x 120 x 110 mm and 160 x 160 x 160 mm",material:" Polypropylene." },
{img:"image/separatoryfunnelholder.jpg", name:"Seperatory Funnel Holder", price:"On Request", description:" This non-corrosive seperatory funnel holder, moulded in polypropylene, has a front opening which provides clear view of the solution and allows unobstructed placement of separatory funnels. Two tapered wedges are provided to ensure firm grip on rods having dia 1/2 inch or 3/8." ,specs:"",material:"polypropylene" } ,
   {img:"image/buchnerfunnel.jpg ", name:"Buchner Funnel ", price:"On Request", description:" Moulded in Polypropylene, these two piece funnels are light weight, easy to clean & autoclavable. The top portion can be snap fitted with the lower one forming a vaccum seal which does not require greasing. The base of the top portion has perforated filter plate.sizes :70 mm,110 mm,90mm.",specs:"sizes :70 mm,110 mm,90mm.",material:" Polypropylene," },
  {img:"image/analyticfunnels.jpg", name:"Analytical Funnel ", price:"On Request", description:" Designed specifically for analytical chemistry, the body of the funnels is 60°. Moulded in PP, these funnels are provided with internal & external ribs to prevent air blockage.Particulars:35 mm,50 mm, 62 mm,75 mm,100mm.Inside φ 35,50,62,75,100.Stem Length :37,50,67,77,95.",specs:"35 mm,50 mm, 62 mm,75 mm,100 mm.Inside φ 35,50,62,75,100.Stem Length :37,50,67,77,95.",material:"PP" },
  {img:"image/powderfunnels.jpg", name:"Powder Funnels", price:"On Request", description:" These polypropylene funnels are best suited for transferring powdered reagents. The unique feature of these funnels is its parallel stem that minimizes bridging of powder. These funnels are steam autoclavable at 121°C.",specs:"",material:"" },
  {img:"image/industrialfunnels.jpg",name:"Industrial Funnels",price:"On Request", description:" Industrial funnels are designed in such a way that they make filling of carboys, drums and barrels very convenient. The handles of these funnels make their handling very easy. ",specs:"",material:"" },
 {img:"image/cryovialinternalthread.jpg",name:"Cryo Vial-Internal Thread ",price:"On Request", description:" cryo vials is this vial which has internal thread in it. The cap fitted with an O-ring screws in to the vial and makes it a leakproof Cryo Vial. These vials are provided with white, prominent graduations and a long marking area for sample identification. ",specs:"",material:"" },
   {img:"image/mcttwinrack.jpg", name:"MCT Twin Rack", price :"On Request" , description:"The transparent top provides an excellent view as well as a protection cover for the tubes stored. Each face of the base has a unique alpha-numeric index for easy identification of the tube.", specs:"0.5 ml & 1.5 ml", material:"Plastic"},
  /*{img:"",name:"",price:"", description:" ",specs:"",material:"" },
 {img:"",name:"",price:"", description:" ",specs:"",material:"" },
 {img:"",name:"",price:"", description:" ",specs:"",material:"" },

  {img:"",name:"",price:"", description:" ",specs:"",material:"" },
 

 {img:"",name:"",price:"", description:" ",specs:"",material:"" },*/


  
  
 
  ];
