var plasticWare = [
  {img:"image/beakersEurodesign.jpg",name :"BEAKER( EURO DESIGN)", price:100, description : "EURO design Beakers, moulded in Polypropylene, too have excellent clarity and very good chemical resistance. These autoclavable Beakers also have prominently raised graduations on the outer surface.It's tapered spout is very helpful in conveniently pouring the solutions"},
  {img:"image/beakers.png",name :"BEAKERS", price: 100, description:"Beakers, moulded in Polypropylene, have excellent clarity and very good chemical resistance. These autoclavable Beakers have prominently raised graduations on the outer surface. Pouring a solution becomes very convenient because of its tapered spout."},
  {img:"image/burette.jpg",name :"BURETTE", price : 100, description: "This Burette has a transparent acrylic pipe and a leak proof TPX stopcock fitted with a self lubricating PTFE plug. Each Burette is individually calibrated to give maximum accuracy. Acrylic body is unaffected by dilute mineral acids & bases except Hydrofluoric acide & Ammonium Hydroxide. The pH range of 1-14 is ideal and can be used up to 5%wt/wt of acids or 30% bases."},
  {img:"image/pipettepump.jpg", name:"PIPETTE PUMP", price: 250, description:"A fast release pipetting device for precise pipetting & zip quick emptying. The knurled thumbwheel can be rotated to draw up or dispense liquids while the releaser may be pushed in for zip-quick emptying. The moulded chuck has silicon rubber collet inside to hold various pipettes of standard sizes. It resists acids & alkalies and can be easily disassembled for thorough cleaning."},
  {img:"image/droppingbottles.jpg", name:"DROPPING BOTTLES", price: 75, description:"Blown in Low Density Polyethylene, Polylab Dropping Bottles dispense small uniform drops of liquids when pressed lightly."},
  {img:"image/dropBottleEuro.jpg", name:"DROPPING BOTTLES (EURO DESIGN)", price:50, description:"These bottles made in low density polyethylene dispense small uniform drops of liquids.The unique feature of these bottles is the screw cap with lid."},
  {img:"image/regentbottelsnarrowmouth.jpg", name:"REGENT BOTTLES (NARROW MOUTH)", price:"15", description:"These Narrow Mouth Regent Bottles are available in polypropylene. The PP bottles are rigid, translucent and have excellent contact clarity. These bottles can be autoclaved filled as well as empty. The polypropylene Cap has a built in seal ring to make these bottles leakproof."},
  {img:"image/reagent_wide.jpg", name:"REAGENT BOTTLES (wide mouth)", price:"20", description:"These wide mouth reagent bottles are available in polypropylene. The PP bottles are rigid, translucent and have excellent contact clarity. These bottles can be autoclaved filled as well as empty. The polypropylene cap has a built in seal ring to make these bottles leekproof"},
  {img:"image/narrowmouthbottel.jpg", name:"NARROW MOUTH BOTTLE", price:"25", description:"This autoclavable bottle, made of polypropylene, can be used for storing & transferring chemicals and other reagents safe & sound."}
  /*{img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""},
  {img:"", name:"", price:"", description:""}*/
];
